spring.application.name=whatsapp-product-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fishdb
spring.datasource.username=postgres
spring.datasource.password=arjun7945
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8081

# WhatsApp API Configuration
whatsapp.api.token=EAAdVasahI1kBQM6BOAw1027RNMt74meyEej8hl8o4k9cXyry3ZCmblniFWTU7XosuDzX9PQZAtxv6NCNdNkNenx9JuZAaYsmTM7VMmaIMWRCPQGNthovYlHLvzdsApmnT7oCUGYFa8iRQndZC7bJc3JchLAfitnE4vzZCd0V1ypsaAkNkXoZAwLXVWfGL04Fr0t9dB6L49leieLgFNAF1Ah3KP4W7V7kRMOaYneN1ZB
whatsapp.api.base-url=https://graph.facebook.com/v20.0
whatsapp.phone-number-id=844388422097905
whatsapp.webhook.verify-token=fish_seller_secret_123
whatsapp.delivery-group-id={YOUR_PERSONAL_PHONE_NUMBER_OR_GROUP_ID}
