-- Migration Script: Add Product Management Stages to AdminFlowStage Check Constraint
-- Date: 2025-12-05
-- Purpose: Update the team_members table check constraint to include new product management stages

-- Step 1: Drop the existing check constraint
ALTER TABLE team_members DROP CONSTRAINT IF EXISTS team_members_current_admin_flow_stage_check;

-- Step 2: Add the updated check constraint with all AdminFlowStage values
ALTER TABLE team_members ADD CONSTRAINT team_members_current_admin_flow_stage_check 
CHECK (current_admin_flow_stage IN (
    'IDLE',
    -- Customer Management
    'CUSTOMER_MENU',
    'AWAITING_CUST_NAME',
    'AWAITING_CUST_PHONE',
    'AWAITING_CUST_WAPHONE',
    'AWAITING_CUST_LOCATION',
    'AWAITING_CUST_UPDATE_SELECTION',
    'AWAITING_CUST_UPDATE_FIELD',
    'AWAITING_CUST_DELETE_CONFIRMATION',
    'CONFIRMING_CUST_ADD',
    'CONFIRMING_CUST_UPDATE',
    -- Delivery Person Management
    'DELIVERY_MENU',
    'AWAITING_DELIVERY_NAME',
    'AWAITING_DELIVERY_PHONE',
    'AWAITING_DELIVERY_WAPHONE',
    'AWAITING_DELIVERY_STATUS',
    'AWAITING_DELIVERY_UPDATE_SELECTION',
    'AWAITING_DELIVERY_UPDATE_FIELD',
    'AWAITING_DELIVERY_DELETE_CONFIRMATION',
    'CONFIRMING_DELIVERY_ADD',
    'CONFIRMING_DELIVERY_UPDATE',
    -- Executive Management
    'EXECUTIVE_MENU',
    'AWAITING_EXEC_NAME',
    'AWAITING_EXEC_PHONE',
    'AWAITING_EXEC_WAPHONE',
    'AWAITING_EXEC_STATUS',
    'AWAITING_EXEC_UPDATE_SELECTION',
    'AWAITING_EXEC_UPDATE_FIELD',
    'AWAITING_EXEC_DELETE_CONFIRMATION',
    'CONFIRMING_EXEC_ADD',
    'CONFIRMING_EXEC_UPDATE',
    -- Assistant Admin Management
    'ASSISTANT_MENU',
    'AWAITING_ASSISTANT_NAME',
    'AWAITING_ASSISTANT_PHONE',
    'AWAITING_ASSISTANT_WAPHONE',
    'AWAITING_ASSISTANT_STATUS',
    'AWAITING_ASSISTANT_UPDATE_SELECTION',
    'AWAITING_ASSISTANT_UPDATE_FIELD',
    'AWAITING_ASSISTANT_DELETE_CONFIRMATION',
    'CONFIRMING_ASSISTANT_ADD',
    'CONFIRMING_ASSISTANT_UPDATE',
    -- Admin Management (For Developers only)
    'ADMIN_MENU',
    'AWAITING_ADMIN_NAME',
    'AWAITING_ADMIN_PHONE',
    'AWAITING_ADMIN_WAPHONE',
    'AWAITING_ADMIN_STATUS',
    'AWAITING_ADMIN_UPDATE_SELECTION',
    'AWAITING_ADMIN_UPDATE_FIELD',
    'AWAITING_ADMIN_DELETE_CONFIRMATION',
    'CONFIRMING_ADMIN_ADD',
    'CONFIRMING_ADMIN_UPDATE',
    -- Product Management (NEW)
    'PRODUCT_MENU',
    'AWAITING_PRODUCT_NAME',
    'AWAITING_PRODUCT_PRICE',
    'AWAITING_PRODUCT_DESCRIPTION',
    'AWAITING_PRODUCT_AVAILABILITY',
    'AWAITING_PRODUCT_IMAGES',
    'CONFIRMING_PRODUCT_ADD',
    'AWAITING_PRODUCT_UPDATE_SELECTION',
    'AWAITING_PRODUCT_DELETE_CONFIRMATION',
    -- Broadcast Management
    'AWAITING_BROADCAST_MESSAGE',
    'CONFIRMING_BROADCAST'
));

-- Verify the constraint was added
SELECT conname, contype, pg_get_constraintdef(oid) 
FROM pg_constraint 
WHERE conname = 'team_members_current_admin_flow_stage_check';
