package com.fishseller.whatsappservice.model.enums;

/**
 * Enum representing different stages in the admin conversation flow
 */
public enum AdminFlowStage {
    IDLE, // Main menu state

    // Customer Management
    CUSTOMER_MENU,
    AWAITING_CUST_NAME,
    AWAITING_CUST_PHONE,
    AWAITING_CUST_WAPHONE,
    AWAITING_CUST_LOCATION,
    AWAITING_CUST_UPDATE_SELECTION,
    AWAITING_CUST_UPDATE_FIELD,
    AWAITING_CUST_DELETE_CONFIRMATION,
    CONFIRMING_CUST_ADD,
    CONFIRMING_CUST_UPDATE,

    // Delivery Person Management
    DELIVERY_MENU,
    AWAITING_DELIVERY_NAME,
    AWAITING_DELIVERY_PHONE,
    AWAITING_DELIVERY_WAPHONE,
    AWAITING_DELIVERY_STATUS,
    AWAITING_DELIVERY_UPDATE_SELECTION,
    AWAITING_DELIVERY_UPDATE_FIELD,
    AWAITING_DELIVERY_DELETE_CONFIRMATION,
    CONFIRMING_DELIVERY_ADD,
    CONFIRMING_DELIVERY_UPDATE,

    // Executive Management
    EXECUTIVE_MENU,
    AWAITING_EXEC_NAME,
    AWAITING_EXEC_PHONE,
    AWAITING_EXEC_WAPHONE,
    AWAITING_EXEC_STATUS,
    AWAITING_EXEC_UPDATE_SELECTION,
    AWAITING_EXEC_UPDATE_FIELD,
    AWAITING_EXEC_DELETE_CONFIRMATION,
    CONFIRMING_EXEC_ADD,
    CONFIRMING_EXEC_UPDATE,

    // Assistant Admin Management
    ASSISTANT_MENU,
    AWAITING_ASSISTANT_NAME,
    AWAITING_ASSISTANT_PHONE,
    AWAITING_ASSISTANT_WAPHONE,
    AWAITING_ASSISTANT_STATUS,
    AWAITING_ASSISTANT_UPDATE_SELECTION,
    AWAITING_ASSISTANT_UPDATE_FIELD,
    AWAITING_ASSISTANT_DELETE_CONFIRMATION,
    CONFIRMING_ASSISTANT_ADD,
    CONFIRMING_ASSISTANT_UPDATE
}
